name=GP8403 DAC Driver
version=1.0.0
author=Eray Eroglu <eray.eroglu@boardoza.com>
maintainer=Boardoza <Boardoza.com>
sentence=Library for GP8403 Dual Channel 12-bit DAC over I2C.
paragraph=This library provides an easy-to-use API for interfacing with the GP8403 dual-channel DAC via I2C. It supports 0-5V and 0-10V voltage output modes and includes built-in functions for signal generation such as smooth sine waves, square waves, and ramp signals.
category=Signal Input/Output
url=https://github.com/Boardoza/GP8403_DAC_Driver
architectures=*